server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "3ZrguQexZQRXtCX8xXPICyhaGFgs6bhdpqrKSb8iQ491QvDsg0+mYDVOcmdFYjYu"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in seconds